# -*- coding: utf-8 -*-
"""Regresi Polinomial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16WnQrUMoJM9NeFXe0-2istFGojjToMFJ
"""

#REGRESI POLINOMIAL

#database 
#x = data, y = Target 
x  = [[ 2 ],[ 3 ],[ 4 ],[ 5 ],[ 6 ],[ 7 ],[ 8 ],[ 9 ],[10],[11]]
y  = [ 4 , 9 , 16 , 25 , 36 , 49 , 64 , 81, 100, 121 ]              #x dipangkat 2

#data uji 
predict = np.array([[55]]) #nilai yang di prediksi 
poly = PolynomialFeatures(degree=2) #ordo yang digunakan
x_=poly.fit_transform(x) #fitting prediksi sumbu
predict_ = poly.fit_transform(predict) #fitting jenis regresi
regr = linear_model.LinearRegression() #meregresi
regr.fit(x_,y) #menentukan grafik

#menampilkan data prediksi 
print ("Prediksi")
print ("input = ", predict)
print ("Output =", regr.predict(predict_))